version: "3.8"

services:
  blockhub:
    container_name: blockhub
    image: blockhub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=/api/v2
      - DOMAIN=blockhub.mmdrza.com
      - ADMIN_EMAIL=mmdrza@usa.com
    volumes:
      - .:/app
    networks:
      - blocknet

networks:
  blocknet:
    driver: bridge