version: '3.8'

services:
  blockhub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blockhub
    restart: unless-stopped
    ports:
      - "80:80"  # HTTP
      - "443:443" # HTTPS
    environment:
      - DOMAIN=blockhub.mmdrza.com  # Set your domain here
      - ADMIN_EMAIL=admin@example.com # Set your admin email
      - VITE_API_BASE_URL=/api/v2
      - TZ=UTC
    volumes:
      - ./data/nginx:/etc/nginx/ssl/nginx.crt
    networks:
      - blocknet

networks:
  blocknet:
    driver: bridge