version: '3.8'

services:
  blockhub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blockhub
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=/api/v2
      - DOMAIN=blockhub.mmdrza.com
      - ADMIN_EMAIL=mmdrza@usa.com
    networks:
      - blockhub_network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

networks:
  blockhub_network:
    driver: bridge
