version: "3.8"

services:
  blockhub:
    container_name: blockhub
    image: blockhub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-9000}:80"
    environment:
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_WORKER_CONNECTIONS=1024
      - PROXY_READ_TIMEOUT=60
      - PROXY_CONNECT_TIMEOUT=60
      - DOMAIN=${DOMAIN:-0.0.0.0}
      - VITE_API_BASE_URL=/api/v2
    restart: unless-stopped
    networks:
      - blocknet

networks:
  blocknet:
    driver: bridge