version: '3.8'

services:
  blockhub:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
    container_name: blockhub
    restart: unless-stopped
    ports:
      - "${PORT:-9000}:9000"
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/certbot
      - ./logs:/var/log/nginx
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@localhost}
      - USE_SSL=${USE_SSL:-false}
      - NODE_ENV=${NODE_ENV:-production}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-/api/v2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - blockhub_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  certbot-etc:
  certbot-var:
  webroot:

networks:
  blockhub_network:
    driver: bridge