version: "3.8"

services:
  blockhub:
    container_name: blockhub
    image: blockhub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-80}:80"
      - "443:443"
    environment:
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_WORKER_CONNECTIONS=1024
      - PROXY_READ_TIMEOUT=60
      - PROXY_CONNECT_TIMEOUT=60
      - DOMAIN=${DOMAIN:-localhost}
      - VITE_API_BASE_URL=/api/v2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    volumes:
      - ./certs:/etc/ssl
      - ./scripts:/scripts
    networks:
      - blocknet

networks:
  blocknet:
    driver: bridge