version: "3.8"

services:
  blockhub:
    container_name: blockhub
    image: blockhub:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PORT=80
      - NODE_ENV=production
      - DOMAIN=${DOMAIN:-blockhub.example.com}
      - VITE_API_BASE_URL=/api/v2
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost/health/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - blocknet
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  blocknet:
    driver: bridge